media: assets

content:
  - name: homepage
    label: Homepage (index.html)
    type: file
    path: index.html
    fields:
      - name: body
        label: Website Content
        type: markdown

  - name: contactpage
    label: Contact Page (contact.html)
    type: file
    path: contact.html
    fields:
      - name: body
        label: Website Content
        type: markdown
